### ISSUE TITLE
100kb larger size due to unicode tables

### ISSUE THREAD

**Issue by egonelbre** [extism/go-pdk#14]
I'm not sure whether to consider this just unfortunate, anyways...

Currently the go-pdk depends on `github.com/valyala/fastjson` and also `strings`, which end up bringing in all of the unicode tables. However, ideally for the minimal use, you wouldn't want the unicode tables to be included.

Although, I agree, it might be difficult to achieve in practice.

**Comment by egonelbre** [comment]
One option here would be to move the http things to a separate package, e.g. `github.com/extism/go-pdk/pdkhttp`

**Comment by bhelx** [comment]
This appears to be covered in #23. but feel free to re-open if not. Or we can file a new issue.

**Comment by bhelx** [comment]
Ping @nilslice to be sure

**Comment by nilslice** [comment]
yea I'm good to close this -- if it becomes critical to save the bytes, we can move the http stuff into another package.
