### ISSUE TITLE
Add `Host.HttpRequest`

### ISSUE THREAD

**Issue by zshipko** [extism/go-pdk#3]
We should add a wrapper around `extism_http_request` to make it more usable from Go.

One blocker here is the lack of JSON support, I think we would either have to generate a JSON object manually or pull in a new dependency.

**Comment by nilslice** [comment]
> One blocker here is the lack of JSON support, I think we would either have to generate a JSON object manually or pull in a new dependency.

Echoing my comment on the AssemblyScript PDK issue.. with the exception that I'm not sure there even is a working JSON option yet in Go to bring in at all. 

For HTTP, it might be possible to take a "standard" definition of a `HttpRequest` (need to find from where..) and use a tool like https://github.com/jedisct1/witx-codegen to create the language-specific domain type to use in the PDK util library we vend to a user.

**Comment by nilslice** [comment]
Closed by #7
