### ISSUE TITLE
strange error handling

### ISSUE THREAD

**Issue by Mcdostone** [extism/go-pdk#33]
Hi,

I've been using extism to implement a plugin system in a rust project and I'm facing a strange behavior regarding error handling when calling a extism plugin function generated with golang. To be honest, I don't know if the issue comes from the rust Extism library or the go-pdk library. 

According to the documentation of this library:
> An Extism export expects an i32 return code. 0 is success and 1 is a failure.

For some reasons, returning`int32` different from 0 doesn't mean the wasm function failed for the rust host program.
Here is the repo to reproduce the steps: https://github.com/Mcdostone/go-pdk-error-handling

| returned code | `setError` | Host       | expected | actual   |
| ------------- | ---------- | ---------- | -------- | -------- |
| 0             | `false`    | rust       | no error | no error |
| 0             | `false`    | extism CLI | no error | no error |
| 0             | `true`     | rust       | ?        | panic    |
| 0             | `true`     | extism CLI | ?        | no error |
| 500           | `false`    | rust       | panic    | no error |
| 500           | `false`    | extism CLI | panic    | panic    |

Let me know if you have any questions.

**Comment by zshipko** [comment]
Hey, thanks for putting the examples together! 

I think returning 0 after setting the error should result in an error, but it does seem like the return codes aren't triggering an error response in the Rust or Go SDKs. I will take a look at this today!

**Comment by zshipko** [comment]
I've just opened https://github.com/extism/cli/pull/92 and https://github.com/extism/extism/pull/727 that should fix your third scenario

**Comment by zshipko** [comment]
Just merged those and verified using extism from git fixes your example - please feel free to re-open if something isn't working correctly

Thanks again for your helpful reproduction of the issue!
