### ISSUE TITLE
Remove Log.Trace as it is not exposed on the Extism CLI

### ISSUE THREAD

**Issue by hilaryRope** [extism/go-pdk#37]
This issue is made of two parts:

- Amend The go-pdk documentation at this line: https://github.com/extism/go-pdk/blob/de6b7b8bb649f16ed1d48b957e10986fa7fb86a7/README.md?plain=1#L196 as it should read `"A warn log!"`
- Remove LogTrace as it does not seem to be exposed on the Extism CLI side and does not come up even if the log level is set to `--log-level=trace`. Here is an example:

```
//export log_stuff
func logStuff() int32 {
	pdk.Log(pdk.LogInfo, "An info log!")
	pdk.Log(pdk.LogDebug, "A debug log!")
	pdk.Log(pdk.LogWarn, "A warn log!")
	pdk.Log(pdk.LogError, "An error log!")
	pdk.Log(pdk.LogTrace, "A trace log!")
	return 0
}

func main() {}
```

Compile it onto `.wasm`:

` tinygo build -o plugin.wasm -target wasi main.go `

and finally:

```
extism call plugin.wasm log_stuff --wasi --log-level=trace

2024/07/12 23:48:44 No runtime detected
2024/07/12 23:48:44 Calling function : log_stuff
2024/07/12 23:48:44 An info log!
2024/07/12 23:48:44 A debug log!
2024/07/12 23:48:44 A warn log!
2024/07/12 23:48:44 An error log!
```

**Comment by hilaryRope** [comment]
Happy to pick this up and resolve it. Long term solution should be to update every SDK and PDK to support trace. There will be a separate ticket for it

**Comment by hilaryRope** [comment]
I will pick this up :)

**Comment by zshipko** [comment]
Thanks! Let us know if you get stuck on anything
