### ISSUE TITLE
Re-instate pdk.LogTrace - as per the set of PRs to enable logTrace across

### ISSUE THREAD

**Issue by hilaryRope** [extism/go-pdk#42]
`logTrace` was temporarily removed as per [here](https://github.com/extism/go-pdk/issues/37), however we have started a serie of PRs to enable it across SDKs and PDKs. While Rust SDK was done and merged [here](https://github.com/extism/extism/pull/747), we need to re-instate `pdk.LogTrace `[here](https://github.com/extism/go-pdk/blob/main/extism_pdk.go#L17) so that the go-sdk PR [here](https://github.com/extism/go-sdk/pull/73) can easily be merged and tests will pass.

**Comment by G4Vi** [comment]
Completed in #43
